/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldRouteImport } from './routes/world'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as FrBlogIndexRouteImport } from './routes/fr/blog/index'
import { Route as FrBlogSlugRouteImport } from './routes/fr/blog/$slug'
import { Route as FrProjectsSlugRouteImport } from './routes/fr/projects/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrBlogIndexRoute = FrBlogIndexRouteImport.update({
  id: '/fr/blog/',
  path: '/fr/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrBlogSlugRoute = FrBlogSlugRouteImport.update({
  id: '/fr/blog/$slug',
  path: '/fr/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrProjectsSlugRoute = FrProjectsSlugRouteImport.update({
  id: '/fr/projects/$slug',
  path: '/fr/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/world': typeof WorldRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/fr/': typeof FrIndexRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/fr/projects/$slug': typeof FrProjectsSlugRoute
  '/fr/blog/': typeof FrBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/world': typeof WorldRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/fr': typeof FrIndexRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/fr/projects/$slug': typeof FrProjectsSlugRoute
  '/fr/blog': typeof FrBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/world': typeof WorldRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/fr/': typeof FrIndexRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/fr/projects/$slug': typeof FrProjectsSlugRoute
  '/fr/blog/': typeof FrBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/world'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog/'
    | '/fr/'
    | '/fr/blog/$slug'
    | '/fr/projects/$slug'
    | '/fr/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/world'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog'
    | '/fr'
    | '/fr/blog/$slug'
    | '/fr/projects/$slug'
    | '/fr/blog'
  id:
    | '__root__'
    | '/'
    | '/world'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog/'
    | '/fr/'
    | '/fr/blog/$slug'
    | '/fr/projects/$slug'
    | '/fr/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorldRoute: typeof WorldRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FrIndexRoute: typeof FrIndexRoute
  FrBlogSlugRoute: typeof FrBlogSlugRoute
  FrProjectsSlugRoute: typeof FrProjectsSlugRoute
  FrBlogIndexRoute: typeof FrBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/blog/': {
      id: '/fr/blog/'
      path: '/fr/blog'
      fullPath: '/fr/blog/'
      preLoaderRoute: typeof FrBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/blog/$slug': {
      id: '/fr/blog/$slug'
      path: '/fr/blog/$slug'
      fullPath: '/fr/blog/$slug'
      preLoaderRoute: typeof FrBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/projects/$slug': {
      id: '/fr/projects/$slug'
      path: '/fr/projects/$slug'
      fullPath: '/fr/projects/$slug'
      preLoaderRoute: typeof FrProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorldRoute: WorldRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  FrIndexRoute: FrIndexRoute,
  FrBlogSlugRoute: FrBlogSlugRoute,
  FrProjectsSlugRoute: FrProjectsSlugRoute,
  FrBlogIndexRoute: FrBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
